"""Analytics and readiness review with strict null semantics."""

from __future__ import annotations

from .contracts import ResearchAnalytics, V7Status, VIPReadinessAssessment


class AutonomousResearchAnalyticsV7:
    def report(
        self,
        *,
        engagement_id: str,
        target_id: str,
        benchmark: dict[str, object],
        commands: int = 0,
        candidates: int = 0,
        evidence_complete: bool = False,
    ) -> ResearchAnalytics:
        scorable = int(benchmark.get("scorable_case_count", 0) or 0)
        valid = bool(benchmark.get("metrics_valid", False)) and scorable > 0 and evidence_complete
        if not valid:
            return ResearchAnalytics(
                engagement_id=engagement_id,
                target_id=target_id,
                benchmark_case_count=int(benchmark.get("scenario_class_count", 0) or 0),
                scorable_case_count=scorable,
                requests_sent=0,
                valid_ground_truth=False,
            )
        return ResearchAnalytics(
            engagement_id=engagement_id,
            target_id=target_id,
            research_efficiency=min(1.0, scorable / max(1, commands)),
            discovery_depth=min(1.0, candidates / max(1, scorable)),
            reasoning_quality=0.5,
            evidence_quality=1.0,
            strategy_adaptation=0.5,
            learning_improvement=0.5,
            benchmark_case_count=int(benchmark.get("scenario_class_count", 0) or 0),
            scorable_case_count=scorable,
            requests_sent=0,
            valid_ground_truth=True,
        )


class VIPReadinessReviewV7:
    def review(
        self,
        *,
        engagement_id: str,
        target_id: str,
        benchmark: dict[str, object],
        analytics: ResearchAnalytics,
        architecture_maturity: str = "mature advisory substrate",
    ) -> VIPReadinessAssessment:
        blockers = [
            "official human signoff is absent",
            "official isolated P10 run gate is closed",
            "external targets and bug bounty scope are prohibited",
        ]
        if int(benchmark.get("scorable_case_count", 0) or 0) == 0:
            blockers.append("controlled benchmark has no scorable complete cases")
        if not analytics.valid_ground_truth:
            blockers.append("ground truth/oracle/proof/replay contract is not complete")
        return VIPReadinessAssessment(
            engagement_id=engagement_id,
            target_id=target_id,
            architecture_maturity=architecture_maturity,
            research_autonomy="advisory commander and specialist reasoning implemented",
            detection_capability="not established from offline blocked benchmark",
            evidence_quality="insufficient for qualification",
            benchmark_performance=(
                f"{benchmark.get('scorable_case_count', 0)} scorable / "
                f"{benchmark.get('blocked_case_count', 0)} blocked"
            ),
            remaining_limitations=(
                "no real-world detection claim",
                "no target execution",
                "no causal evidence generated by this layer",
            ),
            remaining_blockers=tuple(blockers),
            governance_status=(
                "official_isolated_p10_runs_authorized=false; "
                "P10/P9/VIP=NOT_QUALIFIED; Bug Bounty=BLOCKED"
            ),
            status=V7Status.BLOCKED,
        )


__all__ = ["AutonomousResearchAnalyticsV7", "VIPReadinessReviewV7"]
